# Generated by Django 3.1.6 on 2021-03-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_business',
            field=models.CharField(choices=[('u', '普通用户'), ('b', '商家')], default='u', max_length=2, verbose_name='是否商家'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('female', '女'), ('male', '男')], default='male', max_length=10, verbose_name='性别'),
        ),
    ]
