# Generated by Django 3.1.6 on 2021-04-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210327_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('female', '女'), ('male', '男')], default='male', max_length=10, verbose_name='性别'),
        ),
    ]
