# Generated by Django 3.1.6 on 2021-03-27 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_longitude', models.DecimalField(decimal_places=6, max_digits=10, null=True, verbose_name='起点经度')),
                ('end_longitude', models.DecimalField(decimal_places=6, max_digits=10, null=True, verbose_name='终点经度')),
                ('start_latitude', models.DecimalField(decimal_places=6, max_digits=10, null=True, verbose_name='起点纬度')),
                ('end_latitude', models.DecimalField(decimal_places=6, max_digits=10, null=True, verbose_name='终点纬度')),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '轨迹',
                'verbose_name_plural': '轨迹',
            },
        ),
        migrations.CreateModel(
            name='Way',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10, null=True, verbose_name='经度')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10, null=True, verbose_name='纬度')),
                ('w_time', models.DateTimeField(null=True, verbose_name='时间')),
                ('trace_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='traces.trace', verbose_name='轨迹')),
            ],
            options={
                'verbose_name': '路程',
                'verbose_name_plural': '路程',
            },
        ),
    ]
