# Generated by Django 3.1.6 on 2021-04-12 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_time', models.DateTimeField(null=True, verbose_name='时间')),
                ('province', models.CharField(max_length=16, verbose_name='省')),
                ('city', models.CharField(max_length=16, verbose_name='市')),
                ('district', models.CharField(max_length=16, verbose_name='区')),
                ('trace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='traces.trace', verbose_name='轨迹')),
            ],
            options={
                'verbose_name': '位置变换',
                'verbose_name_plural': '位置变换',
            },
        ),
    ]
