# Generated by Django 3.1.6 on 2021-04-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traces', '0002_travel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='district',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='province',
        ),
        migrations.AddField(
            model_name='travel',
            name='now_add',
            field=models.CharField(max_length=258, null=True, verbose_name='位置'),
        ),
    ]
