# Generated by Django 3.1.6 on 2021-03-27 16:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('g_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='商品号')),
                ('g_name', models.CharField(max_length=100, verbose_name='商品名')),
                ('g_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='商品价格')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wl_code', models.CharField(max_length=16, null=True, unique=True, verbose_name='订单号')),
                ('wl_ship', models.CharField(choices=[('HHTT', '天天快递'), ('STO', '申通快递'), ('HTKY', '百世快递'), ('YTO', '圆通快递')], max_length=10, verbose_name='快递公司')),
                ('status', models.CharField(choices=[('1', '待收货'), ('2', '已收货')], default='1', max_length=16, verbose_name='订单状态')),
                ('gnum', models.IntegerField(default=0, verbose_name='商品数量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='价格')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='下单时间')),
                ('province', models.CharField(max_length=16, verbose_name='省')),
                ('city', models.CharField(max_length=16, verbose_name='市')),
                ('district', models.CharField(max_length=16, verbose_name='区')),
                ('address', models.CharField(max_length=100, verbose_name='详细地址')),
                ('belong', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='用户')),
                ('good', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.goods', verbose_name='商品')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
    ]
