# Generated by Django 3.1.6 on 2021-03-27 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210327_2302'),
        ('goods', '0002_auto_20210327_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='shujinn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.business', verbose_name='商家'),
        ),
        migrations.AlterField(
            model_name='order',
            name='wl_ship',
            field=models.CharField(choices=[('HTKY', '百世快递'), ('YTO', '圆通快递'), ('HHTT', '天天快递'), ('STO', '申通快递')], max_length=10, verbose_name='快递公司'),
        ),
        migrations.CreateModel(
            name='BossManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessF', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.business', verbose_name='商家')),
                ('orderF', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.order', verbose_name='订单')),
            ],
        ),
    ]
