# Generated by Django 3.1.6 on 2021-03-27 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20210327_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='g_name',
            field=models.CharField(max_length=100, null=True, verbose_name='商品名'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='g_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='商品价格'),
        ),
        migrations.AlterField(
            model_name='order',
            name='wl_ship',
            field=models.CharField(choices=[('YTO', '圆通快递'), ('HTKY', '百世快递'), ('HHTT', '天天快递'), ('STO', '申通快递')], max_length=10, verbose_name='快递公司'),
        ),
    ]
