# Generated by Django 3.1.6 on 2021-04-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20210327_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('2', '已收货'), ('1', '待收货')], default='1', max_length=16, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='order',
            name='wl_ship',
            field=models.CharField(choices=[('HTKY', '百世快递'), ('STO', '申通快递'), ('YTO', '圆通快递'), ('HHTT', '天天快递')], max_length=10, verbose_name='快递公司'),
        ),
        migrations.DeleteModel(
            name='BossManager',
        ),
    ]
