# Generated by Django 3.1.6 on 2021-04-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20210401_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', '待收货'), ('2', '已收货')], default='1', max_length=16, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='order',
            name='wl_ship',
            field=models.CharField(choices=[('YTO', '圆通快递'), ('HHTT', '天天快递'), ('STO', '申通快递'), ('HTKY', '百世快递')], max_length=10, verbose_name='快递公司'),
        ),
    ]
