# Generated by Django 3.1.6 on 2021-04-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_auto_20210412_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='wl_ship',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('2', '已收货'), ('1', '待收货')], default='1', max_length=16, verbose_name='订单状态'),
        ),
    ]
