# Generated by Django 3.1.6 on 2021-04-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_auto_20210412_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', '待收货'), ('2', '已收货')], default='1', max_length=16, verbose_name='订单状态'),
        ),
    ]
